### PR TITLE
Code review for 1.1

### PR DESCRIPTION
**Pull request by LukeBillington**
Updated the version number to 1.1 to prepare for a code review.

### CODE REVIEW

**Review by nmcayouette — COMMENTED** [review]
// Line 15: I like the type check here. Didn't even think to do that - obviously under thinking it. Good job.
 // Line 41: Great use of the methods to create the different inputs. Your code isn't repetitive at all. Very efficient. *Suggest using a unifier like .toLowerCase or something in order to save an error if the CaSe doesn't match. For example: "{ name: 'test2', type: 'TEXT'}," throws an error when it should be allowed.
 // 138: *Suggest giving the user the valid information and an error message. Might be more clear for a succesful future use.
 
 // Overall, I really like this component. The use of es6 and reusable parts is efficient and clean. Great job.

**Comment by LukeBillington** [comment]
Hey thanks, I'll get right on it! On 138, that should be okay, it's a template for an error message for whenever an error is called, not an error itself, I'll make it a little more semantic though for usability sake.

**Comment by LukeBillington** [comment]
I've also gone ahead and pulled the console.log out of my module itself, didn't think about it from a usability point, so now I'll reflect that change in my example on my readme.

**Comment by nmcayouette** [comment]
Sweet deal! LGTM

**Comment by BHess2653** [comment]
Everything looks good to me.

**Pull request merged**
