### PR TITLE
Add linting, testing, and contributing

### PR DESCRIPTION
**Pull request by LukeBillington**
Added AirBnB style linting, cleaned FormBuilder to satisfy linting
needs. Added contributing, with development and style guide
instructions and dependencies. Added style guide mocha/chai assertion
test. Matched style guide for code examples in readme.

### CODE REVIEW

**Comment by BHess2653** [comment]
I would add .DS_Store to the .gitignore.

**Comment by BHess2653** [comment]
also on line 3 of the package.json version 1.2.0.

**Comment by LukeBillington** [comment]
Thanks, @BHess2653, the changes should be made!

**Comment by BHess2653** [comment]
LGTM

**Pull request merged**
